import {createClient} from "@supabase/supabase-js";

export const supabase = createClient('https://pfxwcaazndqgfekaisrj.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeHdjYWF6bmRxZ2Zla2Fpc3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc3MTQ1NzksImV4cCI6MjAzMzI5MDU3OX0.fIOkcYr8uIgYcbRbYVzjvcLHU6yNC4gPUOcvckWFdL4')
